version: '3.8'

services:
  server1:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=1
      - ACTIVE_SERVERS=1 2 3
    ports:
      - "5001:5000"

  server2:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=2
      - ACTIVE_SERVERS=1 2 3
    ports:
      - "5002:5000"

  server3:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=3
      - ACTIVE_SERVERS=1 2 3
    ports:
      - "5003:5000"

  server4:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=4
    ports:
      - "5004:5000"

  server5:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=5
    ports:
      - "5005:5000"

  server6:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=6
    ports:
      - "5006:5000"

  server7:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=7
    ports:
      - "5007:5000"

  server8:
    build:
      context: .
      dockerfile: Dockerfile.server
    environment:
      - SERVER_ID=8
    ports:
      - "5008:5000"

  load_balancer:
    build:
      context: .
      dockerfile: Dockerfile.load_balancer
    environment:
      - ACTIVE_SERVERS=1 2 3
    ports:
      - "5000:5000"
    depends_on:
      - server1
      - server2
      - server3
      - server4
      - server5
      - server6
      - server7
      - server8
